import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{CalendarDays,Users,Wallet,Settings,Plus,ReceiptText}from'lucide-react';import'./style.css';
const KEY='team-training-demo-v1';
const seed={members:[{id:1,name:'민준',role:'아이'},{id:2,name:'서준',role:'아이'},{id:3,name:'김코치',role:'코치'},{id:4,name:'이코치',role:'코치'}],events:{'2026-10-10':{time:'10:00 ~ 13:00',place:'C운동장',important:'집합시간 꼭 지켜주세요.',attendance:{1:'가능',2:'조정',3:'가능',4:'가능'},expenses:[]}},ledger:[],payments:{}};
function App(){const[d,setD]=useState(()=>JSON.parse(localStorage.getItem(KEY)||'null')||seed);const[tab,setTab]=useState('달력');const[day,setDay]=useState(null);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(d)),[d]);const saveEvent=(date,e)=>setD(x=>({...x,events:{...x.events,[date]:e}}));
return <div className="app"><header><b>주말 훈련 관리</b><span>공유 팀앱</span></header><main>{tab==='달력'&&<Calendar d={d} day={day} setDay={setDay} saveEvent={saveEvent} setD={setD}/>} {tab==='명단'&&<Members d={d} setD={setD}/>} {tab==='납부·회계'&&<Money d={d} setD={setD}/>} {tab==='설정'&&<section><h2>설정</h2><div className="card">현재 버전은 로컬 테스트용입니다.<br/>Firebase 설정을 넣으면 여러 사람이 실시간으로 공유할 수 있습니다.</div></section>}</main><nav>{[['달력',CalendarDays],['명단',Users],['납부·회계',Wallet],['설정',Settings]].map(([n,I])=><button className={tab===n?'on':''} onClick={()=>{setTab(n);setDay(null)}}><I/><small>{n}</small></button>)}</nav></div>}
function Calendar({d,day,setDay,saveEvent,setD}){if(day){let e=d.events[day]||{time:'',place:'',important:'',attendance:{},expenses:[]};const kids=d.members.filter(m=>m.role==='아이');return <section><button className="back" onClick={()=>setDay(null)}>← 달력</button><h2>{day} 훈련</h2><div className="card"><label>훈련 시간<input value={e.time} onChange={x=>saveEvent(day,{...e,time:x.target.value})}/></label><label>훈련 장소<input value={e.place} onChange={x=>saveEvent(day,{...e,place:x.target.value})}/></label></div><div className="card"><h3>📢 코치 공지 이미지</h3><input type="file" accept="image/*" onChange={x=>{let f=x.target.files[0];if(f){let r=new FileReader;r.onload=()=>saveEvent(day,{...e,notice:r.result});r.readAsDataURL(f)}}}/>{e.notice&&<img className="receipt" src={e.notice}/>}<h3>⭐ 중요내용</h3><textarea value={e.important} onChange={x=>saveEvent(day,{...e,important:x.target.value})}/></div><div className="card"><h3>참석 현황 · 아이 가능 {kids.filter(k=>e.attendance[k.id]==='가능').length}명</h3>{d.members.map(m=><div className="person"><span>{m.name} <small>{m.role}</small></span><select value={e.attendance[m.id]||'미입력'} onChange={x=>saveEvent(day,{...e,attendance:{...e.attendance,[m.id]:x.target.value}})}><option>미입력</option><option>가능</option><option>조정</option><option>불가</option></select></div>)}</div><Expenses date={day} e={e} saveEvent={saveEvent} setD={setD}/><Comments e={e} day={day} saveEvent={saveEvent}/></section>}
let dates=Array.from({length:31},(_,i)=>i+1);return <section><h2>2026년 10월</h2><div className="week"><b>일</b><b>월</b><b>화</b><b>수</b><b>목</b><b>금</b><b>토</b></div><div className="grid">{[...Array(4)].map((_,i)=><i key={'x'+i}/>)}{dates.map(n=>{let date=`2026-10-${String(n).padStart(2,'0')}`,e=d.events[date];return <button onClick={()=>setDay(date)}><strong>{n}</strong>{e&&<><small>{e.time?.split(' ')[0]}</small><small>{e.place}</small></>}</button>})}</div><button className="primary" onClick={()=>setDay('2026-10-10')}><Plus/> 훈련 일정 추가</button></section>}
function Expenses({date,e,saveEvent,setD}){function add(){let title=prompt('지출 항목 (예: 숙소비)');if(!title)return;let amount=Number(prompt('금액')||0);let item={id:Date.now(),title,amount,receipt:null};saveEvent(date,{...e,expenses:[...(e.expenses||[]),item]});setD(x=>({...x,ledger:[...x.ledger,{id:item.id,date,type:'지출',title,amount}]}))}return <div className="card"><h3>💰 이날의 비용</h3><b>총 지출 {(e.expenses||[]).reduce((a,b)=>a+b.amount,0).toLocaleString()}원</b><button className="primary" onClick={add}><Plus/> 지출 등록</button>{(e.expenses||[]).map(ex=><div className="expense"><span>{ex.title}<b>{ex.amount.toLocaleString()}원</b></span><label className="upload"><ReceiptText/> 영수증 올리기<input hidden type="file" accept="image/*" onChange={x=>{let f=x.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>saveEvent(date,{...e,expenses:e.expenses.map(q=>q.id===ex.id?{...q,receipt:r.result}:q)});r.readAsDataURL(f)}}/></label>{ex.receipt&&<img className="receipt" src={ex.receipt}/>}</div>)}</div>}
function Comments({e,day,saveEvent}){const[t,setT]=useState('');return <div className="card"><h3>댓글</h3>{(e.comments||[]).map(c=><p>💬 {c}</p>)}<div className="row"><input placeholder="댓글을 입력하세요" value={t} onChange={x=>setT(x.target.value)}/><button onClick={()=>{if(t){saveEvent(day,{...e,comments:[...(e.comments||[]),t]});setT('')}}}>등록</button></div></div>}
function Members({d,setD}){return <section><h2>명단 관리</h2>{d.members.map(m=><div className="card person"><span><b>{m.name}</b> · {m.role}</span><button onClick={()=>setD(x=>({...x,members:x.members.filter(q=>q.id!==m.id)}))}>삭제</button></div>)}<button className="primary" onClick={()=>{let name=prompt('이름');if(name)setD(x=>({...x,members:[...x.members,{id:Date.now(),name,role:confirm('코치인가요?')?'코치':'아이'}]}))}}><Plus/> 회원 추가</button></section>}
function Money({d,setD}){const income=d.ledger.filter(x=>x.type==='입금').reduce((a,b)=>a+b.amount,0),out=d.ledger.filter(x=>x.type==='지출').reduce((a,b)=>a+b.amount,0);function add(type){let title=prompt(type+' 내용');if(!title)return;let amount=Number(prompt('금액')||0);setD(x=>({...x,ledger:[...x.ledger,{id:Date.now(),date:new Date().toISOString().slice(0,10),type,title,amount}]}))}return <section><h2>납부 · 회계</h2><div className="stats"><div>총 입금<b>{income.toLocaleString()}원</b></div><div>총 지출<b>{out.toLocaleString()}원</b></div><div>현재 잔액<b>{(income-out).toLocaleString()}원</b></div></div><div className="row"><button className="primary" onClick={()=>add('입금')}>+ 입금 등록</button><button className="danger" onClick={()=>add('지출')}>- 지출 등록</button></div><div className="card"><h3>전체 입출금 장부</h3>{[...d.ledger].reverse().map(x=><div className="ledger"><span>{x.date}<br/><small>{x.title}</small></span><b>{x.type==='입금'?'+':'-'}{x.amount.toLocaleString()}원</b></div>)}</div><div className="card"><h3>아이별 납부 확인</h3>{d.members.filter(m=>m.role==='아이').map(m=><div className="person"><span>{m.name}</span><span className="paid">납부상태 입력 예정</span></div>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);
